# Generated by Django 5.1.2 on 2024-10-29 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Введите ФИО клиента', max_length=200, verbose_name='ФИО клиента')),
                ('email', models.EmailField(help_text='Введите email клиента', max_length=254, unique=True, verbose_name='Email клиента')),
                ('comment', models.TextField(blank=True, help_text='Введите комментарий клиента', null=True, verbose_name='Комментарий клиента')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Massage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(help_text='Введите тему сообщения', max_length=200, verbose_name='Тема сообщения')),
                ('body', models.TextField(blank=True, help_text='Введите текст сообщения', null=True, verbose_name='Текст сообщения')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_states', models.CharField(choices=[('Created', 'Создана'), ('Launched', 'Запущена'), ('Compleated', 'Завершена')], default='Created', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('sent_at', models.DateTimeField(null=True, verbose_name='Дата и время начала отправки')),
                ('end_send_at', models.DateTimeField(null=True, verbose_name='Дата и время окончания отправки')),
                ('client', models.ManyToManyField(to='MailingService.client', verbose_name='Клиент')),
                ('massage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MailingService.massage', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ['created_at', 'sent_at'],
            },
        ),
    ]
