# Generated by Django 5.1.2 on 2024-10-30 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MailingService', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='name',
            field=models.CharField(help_text='Введите название рассылки', max_length=200, null=True, verbose_name='Название рассылки'),
        ),
    ]
