# Generated by Django 5.1.2 on 2024-12-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MailingService', '0002_mailing_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время начала отправки'),
        ),
    ]
