# Generated by Django 5.1.2 on 2024-12-02 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MailingService', '0003_alter_mailing_created_at_alter_mailing_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='end_send_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время окончания отправки'),
        ),
    ]
