# Generated by Django 5.1.2 on 2024-12-05 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MailingService', '0005_client_owner_mailing_owner_massage_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ['created_at', 'sent_at'], 'permissions': [('can_view_mailing', 'Can view mailing')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
