# Generated by Django 5.1.2 on 2024-12-06 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MailingService', '0006_alter_mailing_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attemts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время попытки')),
                ('state', models.CharField(max_length=15, verbose_name='Статус')),
                ('server_response', models.TextField(verbose_name='Ответ почтового сервера')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MailingService.mailing', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Попытка рассылки',
                'verbose_name_plural': 'Попытки рассылок',
                'ordering': ['datetime', 'mailing'],
            },
        ),
    ]
