# Generated by Django 5.1.2 on 2024-12-06 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MailingService', '0007_attemts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attemts',
            options={'ordering': ['datetime', 'mailing'], 'verbose_name': 'Попытка', 'verbose_name_plural': 'Попытки'},
        ),
    ]
